### ISSUE TITLE
Installing with git fails with ModuleNotFoundError

### ISSUE THREAD

**Issue by adamjorr** [PeRDy/warcraftlogs#1]
I've not attempted manually cloning and installing, but installing via `pip install git+git://github.com/PeRDy/warcraftlogs.git` fails with a `ModuleNotFoundError: No module named 'pip.download'` error. Apparently, importing pip.download was unsupported and has been removed (https://github.com/pypa/pip/issues/5272)

**Comment by perdy** [comment]
Fixed.

Thanks!
